### ISSUE TITLE
truffle test errors are 2 lines off

### ISSUE THREAD

**Issue by jdmaresco** [ConsenSys/truffle#35] opened 2015-09-03 01:12 UTC
@Firescar96 pointed this out first on Gitter and I've confirmed, the error messages are 2 lines off.

e.g.

```bash
  2) Contract: GameRunner joinGame should return 3 when a 3rd person tries to join:
     TypeError: undefined is not a function
    at /Users/jd/Development/fudge/test/gamerunner.js:34:23
```

The error says line 34, but it's actually on line 36. I think it may be because of the way you're adding the global `contract()` method?

https://github.com/ConsenSys/truffle/blob/master/lib/test.es6#L33-L64

**Comment by tcoulter** [comment] 2016-07-22 19:09
This should be fixed. Truffle has removed all reliance on babel, which was the cause. If you are still seeing this error in Truffle 2.0 let me know. Thanks!

**Closed by tcoulter** 2016-07-22 19:09 UTC
