### ISSUE TITLE
Truffle test environment not cleaned up properly

### ISSUE THREAD

**Issue by zweicoder** [ConsenSys/truffle#235] opened 2016-08-11 10:01 UTC
During my tests I realize that unless I redeploy contracts into the blockchain via `truffle migrate --reset`, the state of the contracts are persisted sometimes. 

Specifically running `truffle test afile.js` caused the state to not be properly cleaned up, causing subsequent tests to fail:

```
 truffle test test/src/CheapArrayLib.js
Compiling CheapArrayLib.sol...
Compiling JudgeSubscriber.sol...
Compiling test/CheapArrayLibTest.sol...
Compiling test/JudgeSubImpl.sol...


  Contract: CheapArrayLib
    ✓ should start with an empty array
    ✓ should insertAll elements (104ms)
    ✓ should return the correct size
    ✓ should clear elements (42ms)
    ✓ should throw if idx for get(idx) is out of bounds
    ✓ should still insert properly after clearing (157ms)
    ✓ should return all elements with getAll() (70ms)


  7 passing (2s)

[pewpew:/media/code/ethereum/Judge] test(+104/-247)* ± truffle test test/src/CheapArrayLib.js
Compiling CheapArrayLib.sol...
Compiling JudgeSubscriber.sol...
Compiling test/CheapArrayLibTest.sol...
Compiling test/JudgeSubImpl.sol...


  Contract: CheapArrayLib
    1) should start with an empty array
    > No events were emitted
    ✓ should insertAll elements (97ms)
    2) should return the correct size
    > No events were emitted
    ✓ should clear elements (49ms)
    ✓ should throw if idx for get(idx) is out of bounds
    ✓ should still insert properly after clearing (178ms)
    ✓ should return all elements with getAll() (79ms)

```

I'd be happy to point you guys to the repo if more info is needed

**Comment by tcoulter** [comment] 2016-08-22 20:37
Hi @zweicoder, would love to see the repo. If you can get this to me this week (preferably sooner) I can verify and fix this week. Sounds like a good bug.

**Comment by zweicoder** [comment] 2016-08-23 11:00
@tcoulter [Here](https://github.com/zweicoder/Judge/tree/test) it is. Haven't touched it in a while, but to reproduce you can try:

1.  `npm install && npm build:test` 
2. `truffle test test/src/CheapArrayLib.js`
3. `truffle test` or run 2. again.

Tell me if it doesn't reproduce!

**Comment by tcoulter** [comment] 2016-08-23 16:09
Unfortunately I can't reproduce this. The second run seems to work fine for me.

However, I did find something interesting. Specifically, on this line here: https://github.com/zweicoder/Judge/blob/test/migrations/2_deploy_contracts.js#L6

You shouldn't use `NODE_ENV` in this case -- at least, I wouldn't recommend it. Instead, you should specifically code for the network you're planning to use: e.g., http://truffle.readthedocs.io/en/latest/getting_started/migrations/#network-considerations

In this case, you should use check to see if `network == "test"`, as that would produce the desired result, using a workflow that is also supported by Truffle. `NODE_ENV` might just work, actually, but I can't make any guarantees, but it could also be the cause of the issue.

I'm going to close this one for now. If you continue to run into it, please reopen this ticket or create a new one. Thanks!

**Closed by tcoulter** 2016-08-23 16:09 UTC

**Comment by zweicoder** [comment] 2016-08-23 17:37
@tcoulter  Indeed you are right! I made the amendments you suggested and it works fine now, thanks!

**Comment by tcoulter** [comment] 2016-08-23 17:46
:clap: No problem. :)
