### ISSUE TITLE
Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by LogvinovLeon** [ConsenSys/truffle#339] opened 2017-02-02 12:52 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I'm getting `Cannot read property 'constructor' of undefined` in solidity tests when a contract has a numeric argument.

I started with initial project and substituted `MetaCoin` with a standard token contract: `"standard-token": "1.0.0"`
Then I adjusted tests to test my custom token instead of `MetaCoin`.
```
pragma solidity ^0.4.2;

import "truffle/Assert.sol";
import "truffle/DeployedAddresses.sol";
import "../contracts/TestToken.sol";

contract TestTestToken {

  function testInitialBalanceUsingDeployedContract() {
    uint initialSupply = 10000;
    TestToken ntt = TestToken(DeployedAddresses.TestToken());

    Assert.equal(ntt.balanceOf(tx.origin), initialSupply, "Owner should have 10000 TestToken initially");
  }

  function testInitialBalanceWithNewTestToken() {
    uint initialSupply = 10000;
    TestToken ntt = new TestToken(initialSupply);

    Assert.equal(ntt.balanceOf(tx.origin), initialSupply, "Owner should have 10000 TestToken initially");
  }

}

```

The first test passes, but the second fails with an error:
```
  1 failing

  1) TestTestToken testInitialBalanceWithNewTestToken:
     Uncaught TypeError: Cannot read property 'constructor' of undefined
      at /usr/local/lib/node_modules/truffle/node_modules/truffle-contract/contract.js:89:18
      at Array.forEach (native)
      at /usr/local/lib/node_modules/truffle/node_modules/truffle-contract/contract.js:85:32
      at Array.map (native)
      at Object.decodeLogs (/usr/local/lib/node_modules/truffle/node_modules/truffle-contract/contract.js:44:19)
      at Object.callback (/usr/local/lib/node_modules/truffle/node_modules/truffle-contract/contract.js:166:35)
      at /usr/local/lib/node_modules/truffle/node_modules/truffle-contract/node_modules/web3/lib/web3/method.js:142:25
      at /usr/local/lib/node_modules/truffle/node_modules/truffle-contract/node_modules/web3/lib/web3/requestmanager.js:89:9
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:119:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:64:18)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:354:12)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:509:12)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:469:24)
      at endReadableNT (_stream_readable.js:974:12)



npm ERR! Test failed.  See above for more details.
```

Fixing the `if` in [this place](https://github.com/trufflesuite/truffle-contract/blob/2aceb366dd08646a100fda7ea3733644e10f8273/contract.js#L89) from:
```
if (val.constructor.isBN)
```
to:
```
if (val && val.constructor.isBN)
```
fixed the issue for me and now the test passes, but I'm not sure if it's the proper fix.

## Steps to Reproduce

Described above ^

## Expected Behavior

I expected tests to pass.

## Actual Results

They failed

## Environment

* Operating System: macos
* Truffle version: Truffle v3.0.2
* Ethereum client: -
* node version: -
* npm version: -

**Comment by tcoulter** [comment] 2017-02-02 15:26
Thanks for this bug. Will look into it today

**Comment by tcoulter** [comment] 2017-02-02 15:37
To help me reproduce, can you point me to where you got your standard token
contract, to ensure I'm using the right code?

**Comment by LogvinovLeon** [comment] 2017-02-02 15:38
I did `truffle install example-package-standard-token` and copied the code to my contracts folder, cause Token contract there had the filename AbstractToken and truffle didn't handle it correctly.

**Comment by tcoulter** [comment] 2017-02-02 15:41
Another thing I'd like to fix (the newest Solidity should allow more
flexibility there). Thanks!

**Comment by tcoulter** [comment] 2017-02-02 19:54
Once again, thanks for the issue. I successfully reproduced it and fixed. It was due to a last minute change to event processing that misinterpreted boolean values in indexed events. If you uninstall truffle and reinstall it again the issue should be fixed (the issue was in the truffle-contract dependency, which has been updated). Cheers!

**Closed by tcoulter** 2017-02-02 19:54 UTC

**Comment by john-osullivan** [comment] 2018-12-10 22:08
In case somebody else is Googling and comes across this issue, I got this error when I used the `internal` visibility modifier on a constructor function -- keep 'em `public`!
