### ISSUE TITLE
Can't compile contracts due to 'module' is undefined

### ISSUE THREAD

**Issue by dgoswami75** [ConsenSys/truffle#150] opened 2016-04-30 06:46 UTC
I'm getting an error for 'module' is undefined when I run 'truffle compile' from the project folder.
Any pointers to what might be going wrong? truffle init works fine and creates the project structure as described in the docs.
I'm a newbie to Truffle, so please let me know if I need to provide more info. Attaching the error screenshot
<img width="345" alt="moduleundefined" src="https://cloud.githubusercontent.com/assets/2532215/14936245/4732f144-0eaf-11e6-807d-802c579b738e.png">

**Comment by dgoswami75** [comment] 2016-05-05 19:49
Just wanted to check if anyone can help on the above error. I hadn't been able to get to it for the last few days, but will be getting back to it later today... I need some help with the above error.
Thanks a lot for any input.

**Comment by libertect** [comment] 2016-05-08 12:24
I am having the same issue. Same newbie status. Please help us!

**Comment by vmadrien** [comment] 2016-05-10 09:12
Quick tweak : 

-Find the file truffle.cmd
-Copy the file and rename it (e.g truf.cmd) (in the same repo )
-use truf compile

**Comment by brendan87** [comment] 2016-06-17 04:13
@vmadrien is right, however I took what he/she said literally and tried to run "truf" after renaming it. I think the issue is that the truffle node module is supposed to run to compile the contracts, but what is actually happening is Windows is trying to run the .js file called "truffle", which doesn't do much.
So, to clarify for anyone who is a bit confused (as I was) - rename the file, then run "truffle compile", then change the name back again to get it to compile.

**Comment by brendan87** [comment] 2016-06-17 04:22
@vmadrien is right - what is happening is the OS is trying to run the truffle.js file when you type `truffle compile`, instead of running the 'truffle.cmd' link to the node module that (for me) was in appdata/roaming/npm (which should be on the Windows variable PATH). Go rename that truffle.cmd file and you should be fine. Either that or rename the 'truffle.js' file temporarily before running 'truffle compile' in the project directory.

**Comment by tcoulter** [comment] 2016-06-17 07:06
Interesting. As an alternative, you can always try Git for Windows, which provides the Git BASH terminal. It's guaranteed to work correctly there. https://git-for-windows.github.io/

**Comment by vmadrien** [comment] 2016-06-17 13:53
I should have explained that tweak more :) Thanks @brendan87

**Comment by troygolden** [comment] 2016-07-16 04:03
cant get it to work.  changed name. still wont work

**Comment by tcoulter** [comment] 2016-08-25 17:13
This issue has been fixed on the Truffle master branch and will be released later this week (likely tomorrow). The README has been updated in two places that describe how you can avoid this issue in the future. Thanks for reporting!

http://truffle.readthedocs.io/en/latest/getting_started/installation/#recommendations-for-windows
http://truffle.readthedocs.io/en/latest/advanced/configuration/#resolving-naming-conflicts-on-windows

**Closed** 2016-08-25 17:13 UTC

**Comment by ariolaclint** [comment] 2017-04-06 02:20
Hi Guys,

Download the
Cygwin64 Terminal for windows
then run again truffle compile on truffle directory

![image](https://cloud.githubusercontent.com/assets/11716464/24734904/abe98e9e-1ab2-11e7-815d-2a50b7bb82a0.png)

**Comment by rts-2** [comment] 2017-07-11 15:04
When I rename the file, then I get the error "Could not find suitable configuration file" - is anyone else having this problem?

**Comment by batjko** [comment] 2017-07-29 12:28
I am having this issue, just following the setup of the pet-shop (http://truffleframework.com/boxes/pet-shop), throwing this error when trying to `truffle compile`. 
I'm on Windows 10 64bit.

@tcoulter If it was fixed, I seem to encounter a regression.
Also, the two links posted back in Aug last year are dead now.

I can go and manually rename the truffle.js as suggested, but it would be nice if that weren't necessary.

**Comment by batjko** [comment] 2017-07-29 12:30
Ah, never mind. Found this in the current documentation:
http://truffleframework.com/docs/advanced/configuration#resolving-naming-conflicts-on-windows

**Comment by yuandi0823** [comment] 2017-08-25 16:56
WIN10  use PowerShell is OK

**Comment by masonbrothers** [comment] 2017-09-29 07:21
If you have the same issue on Windows, instead of
> truffle compile
try
> truffle.cmd compile

**Comment by edu-san** [comment] 2017-11-21 21:50
not sure if this get resolved but you can always use truffle.cmd compile

**Comment by bitsabhi** [comment] 2018-02-19 08:16
Either use truffle.cmd compile or go to the /contract directory and use truffle compile .

**Comment by npittsley** [comment] 2018-03-12 11:32
Yep, using 
truffle.cmd compile
worked for me!

**Comment by rishikeshjadhav** [comment] 2018-03-23 06:20
Using truffle.cmd worked for me :)
While reading below helped as well
http://truffleframework.com/docs/advanced/configuration#resolving-naming-conflicts-on-windows

**Comment by reddysuresh78** [comment] 2018-04-22 10:30
I had same problem on windows. But running it from inside the contracts folder worked without any issue.

**Comment by Shuooang** [comment] 2018-04-22 19:49
in windows try ...
'truffle.cmd' 
instead of 'truffle'.

Because of PATH_EXT= .......... .JS 
truffle.js is excuted.

Or remove '.JS' in PATH_EXT .

**Comment by gnidan** [comment] 2018-09-28 21:31
@haghighatcs use `truffle-config.js` instead of `truffle.js` (either rename truffle.js or delete it)

**Comment by rahultelgote1989** [comment] 2019-09-05 20:09
This could be issue with Windows Command Prompt; you can try with Windows Powershell, it worked like a charm for me:
![image](https://user-images.githubusercontent.com/5608778/64376959-167c2180-d047-11e9-99c8-8347498e4f0c.png)

**Comment by RudrikaFichadiya7** [comment] 2020-11-07 10:36
> Interesting. As an alternative, you can always try Git for Windows, which provides the Git BASH terminal. It's guaranteed to work correctly there. https://git-for-windows.github.io/

Thank you It helped me!
