### ISSUE TITLE
Function calls that returns in a throw in testrpc crashes truffle

### ISSUE THREAD

**Issue by MrChico** [ConsenSys/truffle#65] opened 2015-12-19 11:29 UTC
Here is a screenshot of what happens:
![screenshot from 2015-12-17 15 15 27](https://cloud.githubusercontent.com/assets/8930559/11912757/be4ccab0-a64b-11e5-8beb-c85f621ddad4.png)

Basically, whenever a function call ends up in a throw, truffle gives an error message. This makes you unable to test that contracts that should return a throw under certain conditions. Happens with testrpc, but not with geth.

**Comment by tcoulter** [comment] 2016-01-15 18:53
@MrChico What can I do to convince you to try out [ethereumjs-testrpc](https://github.com/ethereumjs/testrpc)?

**Comment by MrChico** [comment] 2016-01-15 18:58
Haha, I have actually moved to the js testrpc now. You underestimate your manipulative powers @tcoulter

**Comment by lastperson** [comment] 2016-03-08 08:20
I think this one is related, please consider the following example:
```
contract('Tester', function(accounts) {
  it('should fail', function(done) {
    (new Promise(function(_rs, _rj) {
      setTimeout(function() { throw 'error'; }, 1);
    })).then(done).catch(done)
  });
  it('should be pending');
});
```
It results in a crash on first test, and never gets to the second.
```
Contract: MultiAccessTester

/usr/lib/node_modules/truffle/node_modules/solc/bin/soljson-latest.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](
error
```
The same suite
```
describe('Tester', function(accounts) {
  it('should fail', function(done) {
    (new Promise(function(_rs, _rj) {
      setTimeout(function() { throw 'error'; }, 1);
    })).then(done).catch(done)
  });
  it('should be pending');
});
```
is handled properly in **mocha** though:
```
MultiAccessTester
    1) should emit Called event
    - should be pending emit Called event


  0 passing (11ms)
  1 pending
  1 failing

  1) MultiAccessTester should emit Called event:
     Error: the string "error" was thrown, throw an Error :)
```

**Comment by tcoulter** [comment] 2016-03-08 16:13
Hi @lastperson - Can you output more information about the first error message? Unfortunately the solc package likes to gobble all unhandled errors and then rethrow them. What you're seeing in the above error is the point in the code where the error is rethrown; however, you're not including the stack trace that follows it. Can you give me that stack trace? Thanks - that'll help me better understand the issue.

**Comment by lastperson** [comment] 2016-03-10 10:31
Hi @tcoulter , thanks for quick reply. The problem is that this is the only output I get. Terminal prompt line appears right after the **error** word.

**Comment by tcoulter** [comment] 2016-08-25 17:36
Hey there. I'm going to close this issue because it's so old, and Truffle has been significantly revamped since then. If you're still having issues, don't hesitate to ask in the [Truffle Gitter}(https://gitter.im/ConsenSys/truffle) or file a new ticket. Thanks!

**Closed** 2016-08-25 17:36 UTC
