### ISSUE TITLE
Problem when using "Build" and "Serve" on Windows

### ISSUE THREAD

**Issue by rfikki** [ConsenSys/truffle#232] opened 2016-08-09 20:28 UTC
Rocky@ASUS MINGW64 ~/truffle/metacoin
$ truffle migrate
Running migration: 1_initial_migration.js
  Deploying Migrations...
  Migrations: 0x21fccf6e9f1bd0d4c6a44040f1853424c3fa7ddd
Saving successful migration to network...
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Deploying ConvertLib...
  ConvertLib: 0x70b2e99ab1dbaadf8cebcdf34b0f8873978820b9
  Linking ConvertLib to MetaCoin
  Deploying MetaCoin...
  MetaCoin: 0x46bc04ea33b5dc9da6db35f5c1369fab0973dd3b
Saving successful migration to network...
Saving artifacts...

Rocky@ASUS MINGW64 ~/truffle/metacoin
$ truffle build
Error: Cannot find module 'C:UsersRocky rufflemetacoiuildcontractsConvertLib.sol.js' from 'C:\Users\Rocky\AppData\Local\Temp'
    at C:\Users\Rocky\AppData\Roaming\npm\node_modules\truffle\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\Rocky\AppData\Roaming\npm\node_modules\truffle\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\Rocky\AppData\Roaming\npm\node_modules\truffle\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\Rocky\AppData\Roaming\npm\node_modules\truffle\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\Rocky\AppData\Roaming\npm\node_modules\truffle\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\Rocky\AppData\Roaming\npm\node_modules\truffle\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by mm-nv** [comment] 2016-08-13 17:14
I have the same issue too right out of the box.  Stock windows 7 box.

**Comment by gauravagarwal07** [comment] 2016-08-14 19:11
does anybody found solution of this issue ?

**Comment by ronazulay** [comment] 2016-08-15 15:43
I had this issue too and it seems to be caused by unescaped backslashes in a require() path.
Not sure if this is the right way to solve this but this patch seems to fix the issue:
```
+++ include_contracts.js        2016-08-15 17:22:27.080241600 +0200
@@ -15,7 +15,7 @@
       Pudding.requireFile(file, function(err, contract) {
         if (err) return finished(err);

-        digest += "  \"" + contract.contract_name + "\": require(\"" + file + "\"),\n";
+        digest += "  \"" + contract.contract_name + "\": require(\"" + (process.platform === 'win32' ? file.split('\\').join('\\\\') : file) + "\"),\n";
         finished();
       });
     }, function(err) {
```

**Comment by tcoulter** [comment] 2016-08-23 22:03
Fixed on master. Thanks for the patch. Will go out with the next release!

**Closed** 2016-08-23 22:02 UTC
Labels: in progress

**Comment by yubi00** [comment] 2017-04-05 03:56
hi guys, thanks for the patch, so in which directory should i put this patch file?Thanks
