### ISSUE TITLE
Large int causes throws to fail during testing. 

### ISSUE THREAD

**Issue by barryWhiteHat** [ConsenSys/truffle#334] opened 2017-01-27 21:50 UTC
- [ https://gitter.im/ConsenSys/truffle?at=588b6bcbdcb66e4f76bae841] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
When passing a large uint throw does not work. 

## Steps to Reproduce
contract
```
 function AddKey(address owner, uint256 PubKey) returns(uint) { throw; }
```
```
var PubKey = 260652911456477803323683869567310326260426673437970818576857965924962545969307
tl.AddKey(owner,PubKey)
``` this does not thorw

set ```
var PubKey = 2606529
tl.AddKey(owner,PubKey)
```
This throws. 

## Expected Behavior

Show throw both times

## Actual Results
Only throws when there is a small int passed

```
Compiling EC.sol...
Compiling TimeLock.sol...
  Contract: TimeLock:
    ✓ check adding new key
  1 passing (171ms)
```
Compiling EC.sol...
Compiling TimeLock.sol...
  Contract: TimeLock: 
    ✓ check adding new key
  1 passing (181ms)
/usr/local/lib/node_modules/truffle/lib/test.js:322
          throw reason;
          ^
Error: VM Exception while processing transaction: invalid JUMP at d572ee0fb129179cf2540b6dad8f56986a6b80bbc24f590d3de6cd657f24c99a/fed18b7fbdbd03a8c1f899fde536844251e9a2f5:2207
    at Object.module.exports.InvalidResponse (/usr/local/lib/node_modules/truffle/node_modules/ether-pudding/node_modules/web3/lib/web3/errors.js:35:16)
    at /usr/local/lib/node_modules/truffle/node_modules/ether-pudding/node_modules/web3/lib/web3/requestmanager.js:86:36
    at request.onreadystatechange (/usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:114:13)
    at dispatchEvent (/usr/local/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/usr/local/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:934:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```


## Environment

* Operating System: Linux dev-s 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

* Truffle version: Truffle v2.1.1
* Ethereum client: testrpc
* node version: v6.2.2
* npm version: 4.2.0

**Comment by tcoulter** [comment] 2017-01-27 22:56
I'm having trouble determining what your test looks like. Can you show that here? Also, would you mind sharing the full contract code? What you typed looks jumbled.

**Comment by barryWhiteHat** [comment] 2017-01-27 23:16
Let me make a cut down version. ;-)

**Comment by barryWhiteHat** [comment] 2017-01-27 23:36
```
contract('TimeLock: ', function(accounts) {

  it("case 1", function() {
    tl = TimeLock.deployed()

    var owner = accounts[0];
    var n = "115445564387450941991481732409838921121340329898388495706040442841335199756800587903149000898261945340856676784874918657347633307906756071132017391584489476929371087400989053221067789100989201919954123911970375286114309401587894170767865638539376215996124429737040410789718880530497880688634519689153366810989";
    tl.AddKey(owner,n)
  });

  it("case 2", function() {
    tl = TimeLock.deployed()
    var owner = accounts[0];
    var n = 115445564387450941991481732409838921121340329898388495706040442841335199756800587903149000898261945340856676784874918657347633307906756071132017391584489476929371087400989053221067789100989201919954123911970375286114309401587894170767865638539376215996124429737040410789718880530497880688634519689153366810989;
    tl.AddKey(owner,n)
  });

/*  it("case 3", function() {
    tl = TimeLock.deployed()

    var owner = accounts[0];
    var n = 123;
    tl.AddKey(owner,n)
  }); */

});
```

```
pragma solidity ^0.4.8;



contract TimeLock {
    function TimeLock() {
    }

    function AddKey(address owner, uint256 PubKey) returns(uint) {
        throw;
    }
}
```

Case 1 and 2 pass when they should fail. Case 3 fails which is the expected behavior. I reinitialized my truffle project and copied the test and contract over.

**Comment by tcoulter** [comment] 2017-02-22 17:58
There's a couple issues here. 

### Your tests aren't actually testing anything

A test needs to assert, or fail when things fail. When there's a failure (like when that `throw` is executed) there's no way for the testing framework to know that because you haven't wired up the test correctly. `tl.AddKey(owner,n)` returns a promise, and you're not making that promise available to the testing framework. To do so, you need to `return` the promise, i.e., 

```
return tl.AddKey(owner,n);
```

If the promise fails, then, the testing framework will know about it and report it successfully. 

This is the cause of your passing tests that should fail; you haven't told the framework about the failure, and so everything else -- i.e., the large integers -- are just a red herring and aren't the actually problem in this case.

However, we might as well address the large integer problem since you mentioned it. 

### You're not correctly representing large integers in Javascript and with web3

Javascript [will only support integers +/- 9007199254740991](http://stackoverflow.com/questions/307179/what-is-javascripts-highest-integer-value-that-a-number-can-go-to-without-losin), so case 2 won't send the integer you're expecting simply because Javascript doesn't support a number that large. Case 1 _likely_ won't send the number you expect because that number is a string, and web3 needs to know that you intend to represent a decimal number with that string and not something else (i.e., a hexadecimal number). web3 *might* know, but to ensure it does, use `web3.toBigNumber(your_number)` to be sure before passing it to your function.

I'm going to go ahead and close this ticket, as this should be the information that you need. Feel free to open a new ticket if you run into an issue.

**Closed by tcoulter** 2017-02-22 17:58 UTC
