### ISSUE TITLE
Aftter truffle init, tests don't work

### ISSUE THREAD

**Issue by jackreichelt** [ConsenSys/truffle#197] opened 2016-07-12 01:53 UTC
We created a brand new project via `truffle init`. Then, after starting a private testnet, unlocking the primary address, starting the miner and running the tests, I get the following error.

```
Contract: MetaCoin
    ✓ should put 10000 MetaCoin in the first account
    1) should call a function that depends on a linked library  
    > No events were emitted
    2) should send coin correctly
    > No events were emitted

1) Contract: MetaCoin should call a function that depends on a linked library  :
     AssertionError: Library function returned unexpeced function, linkage may be broken: expected 0 to equal 20000

2) Contract: MetaCoin should send coin correctly:
     BigNumber Error: new BigNumber() not a number: [object Object]
```

We didn't get to looking at the second error, but for the first one, we got the following info:
```
outCoinBalance: { [String: '10000'] s: 1, e: 4, c: [ 10000 ] }
outCoinBalance.toNumber(): 10000
outCoinBalanceEth: { [String: '0'] s: 1, e: 0, c: [ 0 ] }
metaCoinEthBalance: 0
2 * metaCoinBalance: 20000
```

It looks like `meta.getBalanceInEth.call(accounts[0])`, which is setting `outCoinBalanceEth` is not returning the correct value.

**Comment by tcoulter** [comment] 2016-07-22 16:24
This doesn't seem to be the case anymore with Truffle 2.0.4. I'm trying to do some issues cleanup, so I'm going to close this since I can't reproduce. If this is still an issue for you please reopen and comment. Thanks!

**Closed** 2016-07-22 18:02 UTC

**Comment by dax-classix** [comment] 2016-09-01 11:29
I'm experiencing the same problem with Truffle 2.0.8 using `geth --dev` & `miner.start(1)`.

However tests are passing with `testrpc`.

**Comment by cupuyc** [comment] 2016-11-25 13:23
Same issue happens for me with private miner with geth or ethereumJ node.

**Comment by sarbogast** [comment] 2016-12-29 21:00
Same thing still with Truffle 2.1.1. This issue should really be reopened.

**Comment by fox000002** [comment] 2017-01-18 14:05
The same problem with Truffle 2.1.1 and geth 1.5.4-stable.

**Comment by Jacob-H5** [comment] 2017-02-19 17:12
Same with Truffle 3.1.9 and geth-1.5.9-stable. Running against TestRPC is working fine. Should be reopened.

**Comment by omarsiddiqi** [comment] 2017-02-26 04:52
I am having the same issue truffle v3.1.2. When i deploy using testrpc the library linkage works without any issues. When i deploy using a pvt geth network it doesnt work even though the deployment works without any issues.

**Comment by zihehuang** [comment] 2017-02-28 00:13
For those of you that uses a private net geth for development, configure your genesis block as follows: 
```
{
    "config": {
            "homesteadBlock": 10
    },
    "nonce": "0",
    "difficulty": "0x20000",
    "mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578",
    "coinbase": "0x0000000000000000000000000000000000000000",
    "timestamp": "0x00",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "extraData": "0x",
    "gasLimit": "0x2FEFD8",
    "alloc": {}
}
```
The key point here is the `homesteadBlock`, which enables certain features including `DELEGATECALL`, which is what libraries are dependent on. 

Source: https://blog.ethereum.org/2016/02/29/homestead-release/
