### ISSUE TITLE
`truffle init` in VM shared folder

### ISSUE THREAD

**Issue by xavierlepretre** [ConsenSys/truffle#351] opened 2017-02-07 16:00 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
With Truffle 3.1.1, when I run `truffle init` in a folder that is shared between the VM and its host, I get an error message about `cross-device link not permitted`.

## Steps to Reproduce

* Create a VirtualBox VM with Ubuntu Trusty 64, in this case with Vagrant
* Share a folder between host and VM, in this case named `'/home/vagrant/DAPPS` in VM
* Install Truffle 3.1.1 in VM
* Go to a subfolder of the shared folder in VM, in this case `'/home/vagrant/DAPPS/temp1`
* run `truffle init` in VM

## Expected Behavior

I expect it to create the MetaCoin project.

## Actual Results

```sh
$ truffle init
        Downloading project...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: EXDEV: cross-device link not permitted, rename '/home/vagrant/DAPPS/temp1/1486478769218-3521399717528142/truffle-init-default-master' -> '/tmp/default-11717-22397-hs20ew.pvdy8hbyb9'
    at Error (native)
```

## Environment

* Operating System:
- VM: Linux vagrant-ubuntu-trusty-64 3.13.0-107-generic #154-Ubuntu SMP Tue Dec 20 09:57:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Host: MacOS 10.12.3
- VirtualBox 5.1.14
* Truffle version: 3.1.1
* Ethereum client: TestRPC 3.0.3 but should be irrelevant
* node version: 6.9.5
* npm version: 3.10.10

**Comment by tcoulter** [comment] 2017-02-07 16:11
I've found this error on a Windows machine but I'm surprised you're seeing it on Linux. The issue is that the system-wide temp directory exists on a different physical device than your project directory. During init, the example project is downloaded to the temp directory and then moved to your project directory. I'm not entirely sure why this is an error, and why you can't have cross device links. I'll have to look further into it, but any help would be much appreciated.

**Comment by xavierlepretre** [comment] 2017-02-07 17:38
It looks like some people have covered it in at least one package:

* https://www.npmjs.com/package/mv
* https://www.npmjs.com/package/node-mv

**Comment by locklin** [comment] 2017-02-08 01:21
I actually have this issue in a stock linux-mint-17 system (my /tmp is on a different partition from /home). 
I thought 
npm config set tmp /home/scott/tmp 
should fix things, but it seems to have a hard coded /tmp somewhere in the code.

**Comment by tkeber** [comment] 2017-02-08 10:44
I saw this as well on ubuntu with /home and /tmp in different partitions.

simple workaround is to set the TEMP env var, e.g.
    
    TEMP=~/tmp truffle init

**Comment by tcoulter** [comment] 2017-02-09 17:58
Fixed this by creating our own temporary directory within the current working directory (I'd use the `mv` module, but unfortunately the issue is in the github downloader dependency). Since this was fixed in one of Truffle's dependencies, you can get the updated version by uninstalling then reinstalling Truffle. Truffle's version number will remain the same. 

Cheers! Thanks for the report!

**Closed by tcoulter** 2017-02-09 17:58 UTC
