### ISSUE TITLE
Truffle within Cloud9 online IDE

### ISSUE THREAD

**Issue by inasacu** [ConsenSys/truffle#63] opened 2015-12-10 09:35 UTC
Hi, I am running truffle within Cloud9 online IDE.  I finally got truffle to run but I am getting the below error:

inasacu:~/workspace/Conference (master) $ truffle test
Using environment test.
Compiling contracts...

  Contract: Conference
    ✓ should assert true (136ms)
    ✓ Initial conference settings should match (749ms)

/home/ubuntu/.nvm/versions/node/v4.2.1/bin/truffle: line 20:  2673 Killed                  $TRUFFLE_NPM_LOCATION/node_modules/.bin/babel-node -- $TRUFFLE_NPM_LOCATION/truffle.es6 ${args}

Is this the right place where I should post this or should I go directly threw [link to Cloud9!](http://c9.io) services?

**Comment by tcoulter** [comment] 2015-12-10 16:39
I'm not familiar with cloud9, but it appears something is killing the Truffle process. I'd get Cloud9 involved. Perhaps they would have a recommendation.

**Comment by tcoulter** [comment] 2015-12-10 16:40
The answer to this process might be helpful, but again, not sure. http://stackoverflow.com/questions/27745124/cloud-9-ide-says-killed

**Comment by josiahwood** [comment] 2015-12-11 16:26
I don't know if this will solve your problem, but on my Cloud9 instance with Truffle I sometimes have to re-run `nvm install v5.0.0`.  It seems like Cloud9 somehow reverts my selected version of Nodejs when I haven't used it in a while.  I get this exact error when this happens.

**Comment by josiahwood** [comment] 2015-12-12 04:43
Ah, I actually just needed to run `nvm alias default 5.0.0`.  That way I'm sure to get the same version of nodejs every time a new terminal is created in Cloud9.

**Comment by jeffscottward** [comment] 2015-12-14 23:08
I have upgraded to node v5.2.0 stable.

I got a lot of babel errors and some node-sass errors when installing globally
```
npm WARN install:XXXXXXXX@1.0.7 ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/truffle/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/XXXXXXXX' -> '/usr/local/lib/node_modules/truffle/node_modules/XXXXXXXX'`
```

successfully installed a bunch of stuff but at the end got

`npm ERR! code 1`

**Comment by tcoulter** [comment] 2016-01-15 18:55
Marking this for milestone 0.4.0. Treating this issue as "Truffle using Node 5.0". If I can't reproduce the error easily I'm going to close it -- unless you guys object of course!

**Comment by tcoulter** [comment] 2016-02-04 20:12
I'm not able to reproduce these issues. Please reopen if you guys are having trouble.

**Closed by tcoulter** 2016-02-04 20:12 UTC
